version: '3.9'

services:
  angular-app:
    build:
      context: ./front
    image: bayremboussaidi/front
      
    ports:
      - "4200:80"  # Host:Container
    depends_on:
      - express-app




  express-app:
    build:
      context: ./back  # Update this path to your Express app directory.
    image: bayremboussaidi/back
      
    ports:
      - "8084:8084"
    environment:
      DB_PORT: 3306
      DB_HOST: mysql  # Referencing the MySQL service name
      DB_USER: bayrem
      DB_PASSWORD: 123
      DB_NAME: global
    depends_on:  # Ensures express-app waits for mysql
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"  # Optional, exposes MySQL port outside of Docker
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DATABASE: global
      MYSQL_USER: bayrem
      MYSQL_PASSWORD: 123