

import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, AbstractControl } from '@angular/forms';
import { RepasService } from '../services/repas.service';
import { CommanderepasService } from '../services/commanderepas.service';
import { Router } from '@angular/router';

// Define the Repas interface
interface Repas {
  id?: number;
  nom: string;   // Name of the meal
  prix: number;  // Price of the meal
}

// Define the RepasCommand interface
interface RepasCommand {
  nomR: string;   // Changed to use 'nomR' to align with backend expectations
  commentaire: string;     // Comments
  cin: string;            // Identifier
  quantity: number;       // Quantity of meals
  id?: number;            // Optional ID generated by the server
}

@Component({
  selector: 'app-show-repas',
  templateUrl: './show-rep.component.html',
  styleUrls: ['./show-rep.component.css']
})
export class ShowRepasComponent implements OnInit {
  repasList: Repas[] = []; // List of meals
  displayedColumns: string[] = ['nom',  'prix'];
  displayRepas: boolean = false; // Control the visibility of the repas list
  newRepasForm: FormGroup;
  loading: boolean = false; 
  errorMessage: string | null = null;

  constructor(
    private repasService: RepasService, 
    private fb: FormBuilder, 
    private commande: CommanderepasService,
    private router: Router
  ) {
    // Initialize the form with validators
    this.newRepasForm = this.fb.group({
      nomR: ['', [Validators.required]], // Changed 'nom_du_repas' to 'nomR' for consistency
      commentaire: [' ', Validators.required],
      cin: ['', [Validators.required, Validators.minLength(1)]],
      quantity: [1, [Validators.required, Validators.min(1)]], // Set minimum quantity to 1
    });
  }

  ngOnInit(): void {
    this.displayRepas = true; // Set to true to display repas
    this.loadRepas(); // Fetch repas list on initialization
  }

 goToCentralPage() {
    this.router.navigate(['/dashboard']);
  }
  loadRepas() {
    this.repasService.getAllRepas().subscribe(
      (data: Repas[]) => {
        this.repasList = data.map(item => ({
          id: item.id,
          nom: item.nom,
          prix: item.prix, // Convert price to a number
        }));
      },
      (error) => {
        console.error('Error fetching repas', error);
      }
    );
  }

  existingNameValidator(control: AbstractControl): { [key: string]: boolean } | null {
    const existingNames = this.repasList.map(repas => repas.nom.toLowerCase());

    if (control.value && !existingNames.includes(control.value.toLowerCase())) {
      return { 'nameDoesNotExist': true }; // Error if the meal name doesn't exist
    }
    return null;
  }

  addRepas() {
    if (this.newRepasForm.valid) {
      
      const nomR = this.newRepasForm.value.nomR; 
      const commentaire = this.newRepasForm.value.commentaire;
      const cin = this.newRepasForm.value.cin.toString();
      const quantity = this.newRepasForm.value.quantity;

      // Create a RepasCommand object
      const newRepasCommand: RepasCommand = {
        nomR,      // Changed to map to nomR in backend
        commentaire,
        cin,
        quantity,
      };

      // Set loading state
      this.loading = true;
      this.errorMessage = null; // Clear previous errors

      // Call the service method with the RepasCommand object
      this.commande.addRepasCommand(newRepasCommand).subscribe(
        (data) => {
          // Optimistically add the new repas command to the list
          this.repasList.push({ // Adjust this according to your response structure
            nom: nomR,
            prix: 0 // You might want to adjust this to fetch the correct price or keep it uninitialized
          });
          
          // Reset the form for new input
          this.newRepasForm.reset();
          this.newRepasForm.markAsPristine();
        },
        (error) => {
          console.error('Error adding repas command', error);
          this.errorMessage = 'An error occurred while adding the repas command. Please try again.'; // Set error message
        },
        () => {
          this.loading = false; // Reset loading state
        }
      );
    } else {
      console.warn('Form is not valid');
    }
  }
}