// src/app/commanderepas.service.ts

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';

export interface RepasCommand {
    nomRepas: string;   // Name of the meal
    commentaire: string; // Comments regarding the meal
    cin: string;        // Identifier (ex: customer ID)
    quantity: number;   // Quantity of meals
    id?: number;        // Optional ID, usually generated by the server
}

@Injectable({
    providedIn: 'root'
})
export class CommanderepasService {

    private apiUrl = 'http://localhost:8084/commanderepas'; 

    constructor(private http: HttpClient) { }

    // Method to add a new repas command
    addRepasCommand(command: RepasCommand): Observable<any> {
        return this.http.post(this.apiUrl, command, {
            headers: new HttpHeaders({
                'Content-Type': 'application/json'
            })
        });
    }

    // Method to get all repas commands
    getAllRepasCommands(): Observable<RepasCommand[]> {
        return this.http.get<RepasCommand[]>(this.apiUrl);
    }
}