import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable } from 'rxjs';

export interface CommandeTrans {
  chemin: string;
  departure: string;
  arrivée: string;
  commentaire: string;
  id?: number; // Optional, as id is typically generated by the server
}

@Injectable({
  providedIn: 'root'
})
export class CommandetransService {



    private apiUrl = 'http://localhost:8084/commandetrans'; // Your API URL

    constructor(private http: HttpClient) { }

    // Method to add a new transport command
    addCommandeTrans(commande: CommandeTrans): Observable<any> {
        return this.http.post(this.apiUrl, commande, {
            headers: new HttpHeaders({
                'Content-Type': 'application/json'
            })
        });
    }

    // Method to get all transport commands
    getAllCommandesTrans(): Observable<CommandeTrans[]> {
        return this.http.get<CommandeTrans[]>(this.apiUrl);
    }
}

