import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

interface Transport {
  id?: number;  // Assuming there's an ID for identification, optional if generated by the server
  adresseDest: string;
  dateDepart: string; // Or Date if you want to handle as a Date object
  NbrePlace: string; // Or Time if you want to handle as a Date object
  numID : number;
}

@Injectable({
  providedIn: 'root'
})
export class TransportService {

  private apiUrl = 'http://localhost:8084/transport'; // Replace with your actual API URL

  constructor(private http: HttpClient) { }

  // Method to add a new transport
  add(transport: Transport): Observable<Transport> {
    return this.http.post<Transport>(this.apiUrl, transport);
  }

  // Method to get all transports
  getAll(): Observable<Transport[]> {
    return this.http.get<Transport[]>(this.apiUrl);
  }
}